$("#w1").click(function(){
    $(".p3").slideToggle();
  });
  $("#w2").click(function(){
    $(".p2").slideToggle();
  });
  $("#w3").click(function(){
    $(".p4").slideToggle();
  });
  $("#w4").click(function(){
    $(".p5").slideToggle();
  });
  $("#w5").click(function(){
    $(".p6").slideToggle();
  });
  $("#w6").click(function(){
    $(".p7").slideToggle();
  });
  $("#w7").click(function(){
    $(".p8").slideToggle();
  });
  $("#w8").click(function(){
    $(".p10").slideToggle();
  });
  $("#w9").click(function(){
    $(".p9").slideToggle();
  });
  $("#w10").click(function(){
    $(".p11").slideToggle();
  });
  $("#w11").click(function(){
    $(".p12").slideToggle();
  });
  $("#w12").click(function(){
    $(".p13").slideToggle();
  });
  $("#w13").click(function(){
    $(".p14").slideToggle();
  });