$("#w1").click(function(){
    $(".p3").slideToggle();
  });
  $("#w2").click(function(){
    $(".p2").slideToggle();
  });
  $("#w3").click(function(){
    $(".p4").slideToggle();
  });
  $("#w4").click(function(){
    $(".p5").slideToggle();
  });
  $("#w5").click(function(){
    $(".p6").slideToggle();
  });